name: Tests
on: [push, pull_request]

jobs:
  Windows:
    name: windows-${{ matrix.os-version }}-${{ matrix.build-config }}-${{ matrix.build-arch }}${{ matrix.build-tool }}
    runs-on: windows-${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix:
        os-version: [2019, 2022]
        build-config: [debug, release, relwithdebinfo]
        build-arch: [Win32, x64]
        build-tool: ["", "-T ClangCL"]
        exclude:
        - build-arch: Win32
          build-tool: "-T ClangCL"

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      shell: bash
      run: |
        mkdir build
        cd build
        cmake -A${{ matrix.build-arch }} ${{ matrix.build-tool }} -DCMAKE_BUILD_TYPE=${{ matrix.build-config }} ..

    - name: Build
      shell: bash
      run: |
        cd build
        cmake --build . --config ${{ matrix.build-config }}

    - name: Run
      shell: bash
      run: |
        cd build/result/${{ matrix.build-config }}
        ./test.exe


  Ubuntu:
    name: ubuntu-${{ matrix.os-version }}-${{ matrix.build-config }}-${{ matrix.compiler.cc }}
    runs-on: ubuntu-${{ matrix.os-version }}.04
    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}
    strategy:
      fail-fast: false
      matrix:
        os-version: [20, 22]
        build-config: [debug, release]
        compiler:
        - {
            cc: gcc-11,
            cxx: g++-11,
            install: gcc-11 g++-11
          }
        - {
            cc: clang,
            cxx: clang++,
            install: clang
          }

    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.compiler.install }}

    - uses: actions/checkout@v2

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-config }} ..

    - name: Build
      run: |
        cd build
        cmake --build . --config ${{ matrix.build-config }} -- -j3

    - name: Run
      run: |
        cd build/result/${{ matrix.build-config }}
        ./test

